config/routes.rb
require "monban/constraints/signed_in"
require "monban/constraints/signed_out"

Rails.application.routes.draw do

  constraints Monban::Constraints::SignedIn.new do
    root "dashboards#show", as: :dashboard
  end

  constraints Monban::Constraints::SignedOut.new do
    root "sessions#new"
  end

  resources :galleries do
    resources :images, except: [:index]
  end

  resources :images, only: [] do
    resources :comments, only: [:create]
    resource :like, only: [:create, :destroy]
  end

  resources :tags, only: [:show]
  resource :session, only: [:new, :create, :destroy]
  resources :users, except: [:destroy]
  resources :groups do
    member do
      post "join" => "group_memberships#create"
      delete "leave" => "group_memberships#destroy"
    end
  end
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :group_memberships, dependent: :destroy
  has_many :users, through: :group_memberships
  has_and_belongs_to_many :images, through: :group_images
  belongs_to :user

  validates :name, presence: true

  def add_member(user)
    users << user
  end

  def remove_member(user)
    users.delete(user)
  end

  def self.by_most_recent
    order(created_at: :desc)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :require_login, except: [:index, :show]

  def index
    @groups = Group.all
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.create(group_params)
    @group.add_member(current_user)

    if @group.save
      redirect_to @group
    else
      render :new
    end
  end

  def show
    find_group
  end

  def edit
    find_group
  end

  def update
    find_group
    @group.update(group_params)

    redirect_to @group
  end

  def destroy
    group = find_group
    group.destroy
    flash[:notice] = "left group."

    redirect_to groups_path
  end

private

  def find_group
    @group = Group.find(params[:id])
  end

  def group_params
    params.require(:group).permit(
      :name,
      :description,
      :group_image
    )
  end
end

app/views/groups/_form.html.erb
<%= form_for @group do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div>
    <%= f.label :group_image %>
    <%= f.text_area :group_image %>
  </div>

  <%= f.submit %>
<% end %>

app/views/groups/_group.html.erb
<%= link_to group do %>
  <h2>Group: <%= group.name %>, description: <%= group.description %></h2>

  <%= image_tag group.group_image %></p>
<% end %>

<% if group.users.include? current_user %>
  <%= button_to "Leave this group", leave_group_path(group), method: :delete %></h2>
<% else %>
  <h2><%= button_to "Join this group", join_group_path(group), method: :post %></h2>
<% end %>

<% if group.users.include? current_user %>
  <p>You are in this group.</p>
<% end %>

<h3>Group members: </h3>
<% group.users.each do |user| %>
  <p><%= user.email %></p>
<% end %>

<%= render group.images %>
<hr>

app/views/groups/edit.html.erb
<div class="group">
  <div class="welcome">
    Edit Group <%= @group.name %>
  </div>
</div>
<%= render "form", group: @group %>

app/views/groups/index.html.erb
<div class="group">
  <div class="welcome">
    <p>Welcome to Groups!</p>
    <%= link_to "New group", new_group_path %>
  </div>
</div>
<%= render @groups %>

app/views/groups/new.html.erb
<div class="group">
  <%= render "form", group: @group %>
</div>

<canvas data-processing-sources=<%= asset_path 'wave.pde' %></canvas>

app/views/groups/show.html.erb
<div class="show">
  <%= render @group %>
  <div class="welcome">
    <%= link_to "Edit", edit_group_path(@group) %>
    <%= link_to "Delete", @group, method: :delete, data: { confirm: "are you sure?"} %>
  </div>
</div>