config/routes.rb
require "monban/constraints/signed_in"
require "monban/constraints/signed_out"

Rails.application.routes.draw do

  constraints Monban::Constraints::SignedIn.new do
    root "dashboards#show", as: :dashboard
  end

  constraints Monban::Constraints::SignedOut.new do
    root "sessions#new"
  end

  resources :galleries do
    resources :images, except: [:index]
  end

  resources :images, only: [] do
    resources :comments, only: [:create]
    resource :like, only: [:create, :destroy]
  end

  resources :tags, only: [:show]
  resource :session, only: [:new, :create, :destroy]
  resources :users, except: [:destroy]
  resources :groups do
    member do
      post "join" => "group_memberships#create"
      delete "leave" => "group_memberships#destroy"
    end
  end
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  has_many :images, dependent: :destroy
  validates :name, presence: true, uniqueness: true
  validates :description, presence: true
  belongs_to :user

  def self.by_most_recent
    order(created_at: :desc)
  end
end

app/controllers/galleries_controller.rb
 class GalleriesController < ApplicationController
  before_action :require_login, except: [:index]
  before_filter :require_permission, only: [:edit, :destroy]

  def index
    @galleries = Gallery.all
  end

  def new
    @gallery = Gallery.new
  end

  def create
    @gallery = current_user.galleries.new(gallery_params)

    if @gallery.save
      redirect_to @gallery
    else
      render :new
    end
  end

  def show
    find_gallery
  end

  def edit
    find_gallery
  end

  def update
    find_gallery

    if @gallery.update(gallery_params)
      redirect_to @gallery
    else
      render :edit
    end
  end

  def destroy
    gallery = find_gallery
    gallery.destroy

    redirect_to galleries_path
  end

  private

  def find_gallery
    @gallery = Gallery.find(params[:id])
  end

  def gallery_params
    params.require(:gallery).permit(:name, :description, :cover_image)
  end

  def require_permission
    if current_user != Gallery.find(params[:id]).user
      redirect_to root_path
    end
  end
end

app/views/galleries/_form.html.erb
<%= form_for gallery do |form| %>
  <%= render "application/form_errors", object: gallery %>

  <div>
    <%= form.label :name, "Gallery name: " %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, "Gallery description: " %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :cover_image, "Gallery Cover Image: " %>
    <%= form.text_field :cover_image %>
  </div>

  <div><%= form.submit %></div>
<% end %>

app/views/galleries/_gallery.html.erb
<%= link_to gallery do%>
  <h2>Gallery: <%= gallery.name %>, description: <%= gallery.description %>
  <br>Cover image:</h2><p> <%= image_tag gallery.cover_image %></p>
<% end %>

<h2>Image:</h2>
<% gallery.images.each do |image| %>
  <div>
    <%= link_to (image_tag image.url), gallery_image_path(gallery, image) %>
  </div>
<% end %>
<hr>

app/views/galleries/edit.html.erb
<div class="gallery">
  <div class="welcome">
    Edit <%= @gallery.name %>
  </div>
</div>
<%= render "form", gallery: @gallery %>

app/views/galleries/index.html.erb
<div class="gallery">
  <div class="welcome">
    <p>Welcome to Galleries!</p>
    <%= link_to "New gallery", new_gallery_path %>
  </div>
</div>
<%= render @galleries.by_most_recent %>

app/views/galleries/new.html.erb
<div class="gallery">
  <div class="welcome">New Gallery!<%= @gallery.name %></div>
  <%= render "form", gallery: @gallery %>
</div>
<canvas data-processing-sources=<%= asset_path 'dim.pde' %></canvas>

app/views/galleries/show.html.erb
<div class="show">
  <%= render @gallery %>
  <div class="welcome">
    <%= link_to "Edit", edit_gallery_path(@gallery) %>
    <%= link_to "Delete", @gallery, method: :delete, data: { confirm: "are you sure?"} %>
    <%= link_to "Add an image", new_gallery_image_path(@gallery) %>
  </div>
</div>