config/routes.rb
require "monban/constraints/signed_in"
require "monban/constraints/signed_out"

Rails.application.routes.draw do

  constraints Monban::Constraints::SignedIn.new do
    root "dashboards#show", as: :dashboard
  end

  constraints Monban::Constraints::SignedOut.new do
    root "sessions#new"
  end

  resources :galleries do
    resources :images, except: [:index]
  end

  resources :images, only: [] do
    resources :comments, only: [:create]
    resource :like, only: [:create, :destroy]
  end

  resources :tags, only: [:show]
  resource :session, only: [:new, :create, :destroy]
  resources :users, except: [:destroy]
  resources :groups do
    member do
      post "join" => "group_memberships#create"
      delete "leave" => "group_memberships#destroy"
    end
  end
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :gallery
  belongs_to :user

  has_many :comments, dependent: :destroy
  has_many :users, through: :likes
  has_and_belongs_to_many :groups
  has_many :likes

  acts_as_taggable

  validates :name, presence: true
  validates :description, presence: true, uniqueness: true
  validates :url, presence: true, uniqueness: true

  def self.by_most_recent
    order(created_at: :desc)
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :require_login
  before_filter :require_permission, only: [:edit, :destroy]

  def new
    find_gallery
    @image = @gallery.images.new
  end

  def create
    find_gallery
    @image = @gallery.images.new(image_params)
    @image.user = current_user

    if @image.save
      redirect_to [@gallery,@image]
    else
      render :new
    end
  end

  def show
    find_gallery
    @image = @gallery.images.find(params[:id])
    @comment = Comment.new
  end

  def edit
    find_gallery
    @image = @gallery.images.find(params[:id])
  end

  def update
    find_gallery
    @image = @gallery.images.find(params[:id])

    if @image.update(image_params)
      redirect_to [@gallery, @image]
    else
      render :edit
    end
  end

  def destroy
    gallery = Gallery.find(params[:gallery_id])
    image = gallery.images.find(params[:id])
    image.destroy

    redirect_to gallery
  end

  private

  def image_params
    params.require(:image).permit(
      :name,
      :description,
      :url,
      :tag_list,
      group_ids:[]
      )
  end

  def find_gallery
    @gallery = Gallery.find(params[:gallery_id])
  end

  def require_permission
    if current_user != Image.find(params[:id]).user
      redirect_to root_path
    end
  end
end

app/views/images/_form.html.erb
<%= form_for [gallery, image] do |form| %>
  <%= render "application/form_errors", object: image %>
  <div>
    <%= form.label :name, "Image name: " %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, "Image description: " %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :url, "Image url: " %>
    <%= form.text_field :url %>
  </div>

  <div>
    <%= form.label :tag_list %>
    <%= form.text_field :tag_list %>
  </div>

  <div>
  <%= form.collection_check_boxes :group_ids, current_user.groups, :id, :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/images/_image.html.erb
<h2>Image: <%= image.name %>, description: <%= image.description %></h2>
<%= link_to (image_tag image.url, width:"600"), gallery_image_path(image.gallery, image) %>

<p>TAGS:</p>
<ul>
  <% image.tags.each do |tag| %>
    <li><%= link_to tag.name, tag_path(tag.name) %></li>
  <% end %>
</ul>

<p>LIKES: <%= image.likes.count %></p>

<ul>
  <% image.groups.each do |group| %>
    <li><%= group.name %></li>
  <% end %>
</ul>

<p>upload by <%= image.user.email %></p>

<% image.likes.each do |like| %>
  <li>
    <%= like.user.email %>
  </li>
<% end %>

<% if current_user.liked_images.include? @image %>
  <% flash[:notice] = "You have liked this image." %>
  <%= button_to "unlike", image_like_path(image), method: :delete %>
<% else %>
  <% flash[:notice] = "You have unliked this image." %>
  <%= button_to "like this image", image_like_path(image) %>
<% end %>

<%= render image.comments.by_most_recent %>
<hr>

app/views/images/edit.html.erb
<div class="welcome">Edit<% @image.name %></div>
<%= render "form", image: @image, gallery: @gallery %>

app/views/images/new.html.erb
<div class="image">
  <div class="welcome">New Image!<%= @image.name %></div>
</div>
<%= render "form", image: @image, gallery: @gallery %>

app/views/images/show.html.erb
<div class="image">
  <%= render @image %>

  <div class="welcome">
    <%= link_to "Edit", edit_gallery_image_path(@gallery, @image) %>
    <%= link_to "Delete", gallery_image_path(@gallery, @image),
      method: :delete, data: { confirm: 'Are you sure?' } %>
  </div>
  <br><br>
  <%= form_for [@image, @comment] do |f| %>
    <%= f.label :content, "Add comment: " %>
    <%= f.text_area :content %>
    <%= f.submit %>
  <% end %>
</div>