config/routes.rb
require "monban/constraints/signed_in"
require "monban/constraints/signed_out"

Rails.application.routes.draw do

  constraints Monban::Constraints::SignedIn.new do
    root "dashboards#show", as: :dashboard
  end

  constraints Monban::Constraints::SignedOut.new do
    root "sessions#new"
  end

  resources :galleries do
    resources :images, except: [:index]
  end

  resources :images, only: [] do
    resources :comments, only: [:create]
    resource :like, only: [:create, :destroy]
  end

  resources :tags, only: [:show]
  resource :session, only: [:new, :create, :destroy]
  resources :users, except: [:destroy]
  resources :groups do
    member do
      post "join" => "group_memberships#create"
      delete "leave" => "group_memberships#destroy"
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyPictures</title>
  <%= stylesheet_link_tag 'application', media: 'all'%>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:300' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>

<body>
  <div class="sign-in-out">
    <% if signed_in? %>
      <%= link_to "Sign out", session_path, method: :delete %>
    <% else %>
      <b><%= link_to "Sign Up", new_user_path %></b><br>
      <b><%= link_to "Sign in", new_session_path %></b>
    <% end %>
  </div>

   <div class="menu">
     <%= link_to "Galleries", galleries_path %>
     <%= link_to "Groups", groups_path %>
      <%= link_to "Users", users_path %>
     <%= link_to "Settings", root_path %>
   </div>

  <section class="container">
    <%= yield %>
  </section>

  <p class="footer"><a href="mailto:abbyzhangnyc@gmail.com">Copyright© Abby Biying Zhang</a></p>
</body>
</html>